server:
  http.port: 8080
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:ubisoft.p12
    key-store-type: PKCS12
    key-store-password: password
    key-alias: ubisoft
security:
  oauth2:
    client:
      clientId: client-id-from-fb
      clientSecret: client-secret-from-fb
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
      